#!/bin/bash

cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-camera
cordova plugin add cordova-plugin-uniquedeviceid
cordova plugin add cordova-plugin-vibration
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-device-motion
cordova plugin add cordova-plugin-device-orientation
cordova plugin add cordova-plugin-dialogs
cordova plugin add cordova-plugin-globalization
cordova plugin add cordova-plugin-media
cordova plugin add cordova-plugin-network-information
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-whitelist

if [ -f ./phonegap-install-custom-plugins ]; then
    source ./phonegap-install-custom-plugins
fi
